# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('health', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=30)),
                ('life', models.IntegerField(default=30)),
                ('deck', models.ManyToManyField(related_name='moncul2', to='deck.Card')),
                ('hand', models.ManyToManyField(related_name='moncul', to='deck.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cardType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.CardType'),
        ),
        migrations.AddField(
            model_name='card',
            name='effect',
            field=models.ManyToManyField(to='deck.Effect'),
        ),
    ]
