# Generated by Django 2.0 on 2018-02-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='description',
        ),
        migrations.RemoveField(
            model_name='player',
            name='cardCollection',
        ),
        migrations.RemoveField(
            model_name='player',
            name='deckCollection',
        ),
        migrations.AddField(
            model_name='player',
            name='cardcollection',
            field=models.ManyToManyField(related_name='cardcollection', to='deck.Card'),
        ),
        migrations.AddField(
            model_name='player',
            name='deckcollection',
            field=models.ManyToManyField(related_name='deckcollection', to='deck.Deck'),
        ),
    ]
