# Generated by Django 2.0 on 2018-01-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_auto_20171214_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardTypeAdmin',
        ),
    ]
