# Generated by Django 2.0 on 2018-02-25 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_auto_20180225_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cardType',
        ),
        migrations.AddField(
            model_name='card',
            name='cardtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deck.Cardtype'),
        ),
    ]
