# Generated by Django 2.0 on 2018-01-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0002_auto_20180126_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='description',
        ),
    ]
