# Generated by Django 2.0 on 2018-02-25 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0003_auto_20180225_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deck.Cardtype'),
        ),
    ]
