# Generated by Django 2.0 on 2018-01-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0004_auto_20180112_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.ManyToManyField(related_name='card', to='deck.Card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cardType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deck.CardType'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='deck',
        ),
        migrations.AddField(
            model_name='player',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deck.Deck'),
        ),
    ]
