# Generated by Django 2.0 on 2018-01-19 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deck', '0006_auto_20180112_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=30)),
                ('life', models.IntegerField(default=30)),
                ('cardCollection', models.ManyToManyField(related_name='cardCollection', to='deck.Card')),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deck', to='deck.Deck')),
                ('deckCollection', models.ManyToManyField(related_name='deckCollection', to='deck.Deck')),
                ('hand', models.ManyToManyField(related_name='main', to='deck.Card')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
