# Generated by Django 2.0 on 2018-01-19 10:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deck', '0007_auto_20180119_1142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Player',
        ),
    ]
