# Generated by Django 2.0 on 2018-01-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0008_auto_20180119_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.RemoveField(
            model_name='player',
            name='life',
        ),
        migrations.RemoveField(
            model_name='player',
            name='pseudo',
        ),
    ]
