# Generated by Django 2.0 on 2018-01-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0009_auto_20180119_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.ImageField(default='static/img/card/deck.jpg', upload_to='static/img/card'),
        ),
    ]
