# Generated by Django 2.0 on 2018-02-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('hp', models.IntegerField(default=30)),
                ('hand', models.TextField(default=None)),
                ('deck', models.TextField(default=None)),
                ('board', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playersHP', models.IntegerField(default=30)),
                ('startingHand', models.IntegerField(default=3)),
                ('spellUse', models.BooleanField(default=True)),
                ('monstersBoard', models.IntegerField(default=7)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='game.GamePlayer'),
        ),
    ]
