# Generated by Django 2.0 on 2018-01-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardTypeAdmin',
        ),
    ]
