# Generated by Django 2.0 on 2018-01-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_delete_cardtypeadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cardType',
        ),
        migrations.RemoveField(
            model_name='card',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='player',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hand',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='CardType',
        ),
        migrations.DeleteModel(
            name='Effect',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
