# Generated by Django 2.0 on 2018-01-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0003_auto_20180112_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playersHP', models.IntegerField(default=30)),
                ('startingHand', models.IntegerField(default=3)),
                ('spellUse', models.BooleanField(default=True)),
                ('monstersBoard', models.IntegerField(default=7)),
            ],
        ),
    ]
