# Generated by Django 2.0 on 2018-01-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20180125_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(default=None, to='game.GamePlayer'),
        ),
    ]
